image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - docker pull <your/docker:image>
    - >
      docker run \
        -e CI_PROJECT_ID="$CI_PROJECT_ID" \
        -e CI_PROJECT_NAME="$CI_PROJECT_NAME" \
        -e CI_MERGE_REQUEST_SOURCE_BRANCH_NAME="$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" \
        -e CI_COMMIT_BRANCH="$CI_COMMIT_BRANCH" \
        -e CI_MERGE_REQUEST_IID="$CI_MERGE_REQUEST_IID" \
        -e CI_PROJECT_VISIBILITY="$CI_PROJECT_VISIBILITY" \
        -e GITLAB_ACCESS_TOKEN="$GITLAB_ACCESS_TOKEN" \
        -e GITLAB_USER_LOGIN="$GITLAB_USER_LOGIN" \
        -e CT_BASE_URL="$CT_BASE_URL" \
        -e CT_TOKEN="$CT_TOKEN" \
        -e CT_ORGANIZATION="$CT_ORGANIZATION" \
        -e FAILED_ARGS='{"max_number_of_critical":1222,"max_number_of_high":11111,"weakness_is":".*imjection","condition":"AND"}' \
        <your/docker:image>
