name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build --no-cache -t codethreatdoc/codethreat-gitlab-job:${TAG} .
          docker push codethreatdoc/codethreat-gitlab-job:${TAG}
          docker tag codethreatdoc/codethreat-gitlab-job:${TAG} codethreatdoc/codethreat-gitlab-job:latest
          docker push codethreatdoc/codethreat-gitlab-job:latest
